misc/Makefile.brcmstb: more resilient way for bundling stbtools tar-ball
Since the introduction of the post-receive hook for the stbtools repo,
tar-balls are being generated automatically and reliably. Therefore,
using these source tar-balls as first choice in releases makes sense.

In the past, generating the tar-ball on the fly was more reliable.
But, with the aforementioned change, this is no longer the case. The
dl/brcm-pl/git repo is no longer being used by default during builds,
so it is also no longer kept up to date by the build system. As a
result, it might be missing relevant commits, and trying to generate
the stbtools tar-ball from it might well fail.

Because it makes sense to use the gen_tar_ball.sh script as a fallback
mechanism, we want to keep it around, but we must ensure the repo is up
to date before we are trying to use it.

Also add some error checking while we are at it.

refs #SWLINUX-6363

Signed-off-by: Markus Mayer <mmayer@broadcom.com>

diff --git a/misc/Makefile.brcmstb b/misc/Makefile.brcmstb
--- a/misc/Makefile.brcmstb
+++ b/misc/Makefile.brcmstb
@@ -152,14 +152,23 @@ brcmstb-release: brcmstb-diffs linux-diffs linux-release
 	$(BRCM_COMPRESS) $(SRC_DST)/buildroot-$(DOTVERSION).tar
 	ln -s buildroot-$(DOTVERSION).tar.bz2 \
 		$(SRC_DST)/rootfs-$(DOTVERSION).tar.bz2
-	# Use stbtools script to generate the stbtools tar-ball, if it exists.
-	# Fall back to the tar-ball Buildroot generated, if it doesn't.
-	if [ -x $(STBTOOLS_GEN_TAR) ]; then \
-		$(STBTOOLS_GEN_TAR) $(STBTOOLS_VERSION) $(SRC_DST); \
-	else \
+	# Use the downloaded stbtools tar-ball if it exists, generate a new one
+	# if necessary, and bail if neither of these two options works.
+	if [ -e $(STBTOOLS_SRC_PATH)/stbtools-$(STBTOOLS_VERSION).tar.gz ]; then \
 		echo "Copying stbtools-$(STBTOOLS_VERSION).tar.gz..."; \
 		cp -p $(STBTOOLS_SRC_PATH)/stbtools-$(STBTOOLS_VERSION).tar.gz \
 			$(SRC_DST); \
+	elif [ -x $(STBTOOLS_GEN_TAR) ]; then \
+		echo "Generating stbtools-$(STBTOOLS_VERSION).tar.gz..."; \
+		(cd $(STBTOOLS_SRC_PATH)/git; git checkout master; git pull); \
+		$(STBTOOLS_GEN_TAR) $(STBTOOLS_VERSION) $(SRC_DST); \
+		if [ $$? != 0 ]; then \
+			echo "Error generating tar-ball." 1>&2; \
+			exit 1; \
+		fi; \
+	else \
+		echo "Can't bundle stbtools-$(STBTOOLS_VERSION).tar.gz." 1>&2; \
+		exit 1; \
 	fi
 
 brcmstb-%:
